### ISSUE TITLE
Config file of DeIT-B/16

### ISSUE THREAD

**Issue by shashankvkt** [Beckschen/TransMix#14]
Thanks for this sharing your amazing work. I was trying to train DeIT-B/16 from scratch on ImageNet-1k using the hyperparams reported in your paper. I'm pretty sure I'm missing something, but I'm unable to reach 82.4%. With the hyperparams I use, I get around 78.6% which is even worse than DeIT-S/16.

Could you please share the training command line for DeIT-B/16 or share the config file for the same?
Thanks a lot.

**Comment by kevin-ssy** [comment]
Hi sorry for the late reply. I just add the training [config](https://github.com/Beckschen/TransMix/blob/main/configs/deit_b_transmix.yaml) for deit_b. Hope it can help.
