### ISSUE TITLE
how to get the attention or heat map of swin-transformer?

### ISSUE THREAD

**Issue by choresefree** [Beckschen/TransMix#5]
hello, authors!
Recently, I have been interested in swin-transformer. However, the heat map I got is very unreasonable. I see that you had worked on swin-transformer, so I want to know your ways of drawing heat map or attention map of swin-transformer.
I would be grateful if you could give me the answer.

**Comment by Beckschen** [comment]
Hello,

Thanks for your interests. Please refer to Section 4.5 of the paper, which details how we generalized TransMix to SwinTransformer.
