### ISSUE TITLE
The description of "lam = (lam0 + lam1) / 2 # ()+(b,) ratio=0.5"

### ISSUE THREAD

**Issue by fistyee** [Beckschen/TransMix#7]
I carefully checked the definition of lam in your paper, but I didn't  find the description of "lam = (lam0 + lam1) / 2 # ()+(b,) ratio=0.5".So, are you using half of the origin lam and half of the attention lam for the final lam?  Thanks

**Comment by kevin-ssy** [comment]
Hi,

Yes. We mentioned this in Section 4.1 of the paper:

> To ease implementation, TransMix shares the same cropped region with CutMix for the input, whereas the label assignment is the mean of both methods.
